export const testjson = {
  products: [
    {
      id: 1,
      title: "iPhone 9",
      description: "An apple mobile which is nothing like apple",
      price: 549,
      discountPercentage: 12.96,
      rating: 4.69,
      stock: 94,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/1/1.jpg",
        "https://i.dummyjson.com/data/products/1/2.jpg",
        "https://i.dummyjson.com/data/products/1/3.jpg",
        "https://i.dummyjson.com/data/products/1/4.jpg",
        "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
      ],
    },
    {
      id: 2,
      title: "iPhone X",
      description:
        "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
      price: 899,
      discountPercentage: 17.94,
      rating: 4.44,
      stock: 34,
      brand: "Apple",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/2/1.jpg",
        "https://i.dummyjson.com/data/products/2/2.jpg",
        "https://i.dummyjson.com/data/products/2/3.jpg",
        "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
      ],
    },
    {
      id: 3,
      title: "Samsung Universe 9",
      description:
        "Samsung's new variant which goes beyond Galaxy to the Universe",
      price: 1249,
      discountPercentage: 15.46,
      rating: 4.09,
      stock: 36,
      brand: "Samsung",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
      images: ["https://i.dummyjson.com/data/products/3/1.jpg"],
    },
    {
      id: 4,
      title: "OPPOF19",
      description: "OPPO F19 is officially announced on April 2021.",
      price: 280,
      discountPercentage: 17.91,
      rating: 4.3,
      stock: 123,
      brand: "OPPO",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/4/1.jpg",
        "https://i.dummyjson.com/data/products/4/2.jpg",
        "https://i.dummyjson.com/data/products/4/3.jpg",
        "https://i.dummyjson.com/data/products/4/4.jpg",
        "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
      ],
    },
    {
      id: 5,
      title: "Huawei P30",
      description:
        "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
      price: 499,
      discountPercentage: 10.58,
      rating: 4.09,
      stock: 32,
      brand: "Huawei",
      category: "smartphones",
      thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/5/1.jpg",
        "https://i.dummyjson.com/data/products/5/2.jpg",
        "https://i.dummyjson.com/data/products/5/3.jpg",
      ],
    },
    {
      id: 6,
      title: "MacBook Pro",
      description:
        "MacBook Pro 2021 with mini-LED display may launch between September, November",
      price: 1749,
      discountPercentage: 11.02,
      rating: 4.57,
      stock: 83,
      brand: "Apple",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
      images: [
        "https://i.dummyjson.com/data/products/6/1.png",
        "https://i.dummyjson.com/data/products/6/2.jpg",
        "https://i.dummyjson.com/data/products/6/3.png",
        "https://i.dummyjson.com/data/products/6/4.jpg",
      ],
    },
    {
      id: 7,
      title: "Samsung Galaxy Book",
      description:
        "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
      price: 1499,
      discountPercentage: 4.15,
      rating: 4.25,
      stock: 50,
      brand: "Samsung",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/7/1.jpg",
        "https://i.dummyjson.com/data/products/7/2.jpg",
        "https://i.dummyjson.com/data/products/7/3.jpg",
        "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
      ],
    },
    {
      id: 8,
      title: "Microsoft Surface Laptop 4",
      description:
        "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
      price: 1499,
      discountPercentage: 10.23,
      rating: 4.43,
      stock: 68,
      brand: "Microsoft Surface",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/8/1.jpg",
        "https://i.dummyjson.com/data/products/8/2.jpg",
        "https://i.dummyjson.com/data/products/8/3.jpg",
        "https://i.dummyjson.com/data/products/8/4.jpg",
        "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
      ],
    },
    {
      id: 9,
      title: "Infinix INBOOK",
      description:
        "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
      price: 1099,
      discountPercentage: 11.83,
      rating: 4.54,
      stock: 96,
      brand: "Infinix",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/9/1.jpg",
        "https://i.dummyjson.com/data/products/9/2.png",
        "https://i.dummyjson.com/data/products/9/3.png",
        "https://i.dummyjson.com/data/products/9/4.jpg",
        "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
      ],
    },
    {
      id: 10,
      title: "HP Pavilion 15-DK1056WM",
      description:
        "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
      price: 1099,
      discountPercentage: 6.18,
      rating: 4.43,
      stock: 89,
      brand: "HP Pavilion",
      category: "laptops",
      thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      images: [
        "https://i.dummyjson.com/data/products/10/1.jpg",
        "https://i.dummyjson.com/data/products/10/2.jpg",
        "https://i.dummyjson.com/data/products/10/3.jpg",
        "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
      ],
    },
    {
      id: 11,
      title: "perfume Oil",
      description:
        "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
      price: 13,
      discountPercentage: 8.4,
      rating: 4.26,
      stock: 65,
      brand: "Impression of Acqua Di Gio",
      category: "fragrances",
      thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/11/1.jpg",
        "https://i.dummyjson.com/data/products/11/2.jpg",
        "https://i.dummyjson.com/data/products/11/3.jpg",
        "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
      ],
    },
    {
      id: 12,
      title: "Brown Perfume",
      description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
      price: 40,
      discountPercentage: 15.66,
      rating: 4,
      stock: 52,
      brand: "Royal_Mirage",
      category: "fragrances",
      thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/12/1.jpg",
        "https://i.dummyjson.com/data/products/12/2.jpg",
        "https://i.dummyjson.com/data/products/12/3.png",
        "https://i.dummyjson.com/data/products/12/4.jpg",
        "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
      ],
    },
    {
      id: 13,
      title: "Fog Scent Xpressio Perfume",
      description:
        "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
      price: 13,
      discountPercentage: 8.14,
      rating: 4.59,
      stock: 61,
      brand: "Fog Scent Xpressio",
      category: "fragrances",
      thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/13/1.jpg",
        "https://i.dummyjson.com/data/products/13/2.png",
        "https://i.dummyjson.com/data/products/13/3.jpg",
        "https://i.dummyjson.com/data/products/13/4.jpg",
        "https://i.dummyjson.com/data/products/13/thumbnail.webp",
      ],
    },
    {
      id: 14,
      title: "Non-Alcoholic Concentrated Perfume Oil",
      description:
        "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
      price: 120,
      discountPercentage: 15.6,
      rating: 4.21,
      stock: 114,
      brand: "Al Munakh",
      category: "fragrances",
      thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/14/1.jpg",
        "https://i.dummyjson.com/data/products/14/2.jpg",
        "https://i.dummyjson.com/data/products/14/3.jpg",
        "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
      ],
    },
    {
      id: 15,
      title: "Eau De Perfume Spray",
      description:
        "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
      price: 30,
      discountPercentage: 10.99,
      rating: 4.7,
      stock: 105,
      brand: "Lord - Al-Rehab",
      category: "fragrances",
      thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/15/1.jpg",
        "https://i.dummyjson.com/data/products/15/2.jpg",
        "https://i.dummyjson.com/data/products/15/3.jpg",
        "https://i.dummyjson.com/data/products/15/4.jpg",
        "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
      ],
    },
    {
      id: 16,
      title: "Hyaluronic Acid Serum",
      description:
        "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
      price: 19,
      discountPercentage: 13.31,
      rating: 4.83,
      stock: 110,
      brand: "L'Oreal Paris",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/16/1.png",
        "https://i.dummyjson.com/data/products/16/2.webp",
        "https://i.dummyjson.com/data/products/16/3.jpg",
        "https://i.dummyjson.com/data/products/16/4.jpg",
        "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
      ],
    },
    {
      id: 17,
      title: "Tree Oil 30ml",
      description:
        "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
      price: 12,
      discountPercentage: 4.09,
      rating: 4.52,
      stock: 78,
      brand: "Hemani Tea",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/17/1.jpg",
        "https://i.dummyjson.com/data/products/17/2.jpg",
        "https://i.dummyjson.com/data/products/17/3.jpg",
        "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
      ],
    },
    {
      id: 18,
      title: "Oil Free Moisturizer 100ml",
      description:
        "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
      price: 40,
      discountPercentage: 13.1,
      rating: 4.56,
      stock: 88,
      brand: "Dermive",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/18/1.jpg",
        "https://i.dummyjson.com/data/products/18/2.jpg",
        "https://i.dummyjson.com/data/products/18/3.jpg",
        "https://i.dummyjson.com/data/products/18/4.jpg",
        "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
      ],
    },
    {
      id: 19,
      title: "Skin Beauty Serum.",
      description:
        "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
      price: 46,
      discountPercentage: 10.68,
      rating: 4.42,
      stock: 54,
      brand: "ROREC White Rice",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/19/1.jpg",
        "https://i.dummyjson.com/data/products/19/2.jpg",
        "https://i.dummyjson.com/data/products/19/3.png",
        "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
      ],
    },
    {
      id: 20,
      title: "Freckle Treatment Cream- 15gm",
      description:
        "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
      price: 70,
      discountPercentage: 16.99,
      rating: 4.06,
      stock: 140,
      brand: "Fair & Clear",
      category: "skincare",
      thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/20/1.jpg",
        "https://i.dummyjson.com/data/products/20/2.jpg",
        "https://i.dummyjson.com/data/products/20/3.jpg",
        "https://i.dummyjson.com/data/products/20/4.jpg",
        "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
      ],
    },
    {
      id: 21,
      title: "- Daal Masoor 500 grams",
      description: "Fine quality Branded Product Keep in a cool and dry place",
      price: 20,
      discountPercentage: 4.81,
      rating: 4.44,
      stock: 133,
      brand: "Saaf & Khaas",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.png",
      images: [
        "https://i.dummyjson.com/data/products/21/1.png",
        "https://i.dummyjson.com/data/products/21/2.jpg",
        "https://i.dummyjson.com/data/products/21/3.jpg",
      ],
    },
    {
      id: 22,
      title: "Elbow Macaroni - 400 gm",
      description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
      price: 14,
      discountPercentage: 15.58,
      rating: 4.57,
      stock: 146,
      brand: "Bake Parlor Big",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/22/1.jpg",
        "https://i.dummyjson.com/data/products/22/2.jpg",
        "https://i.dummyjson.com/data/products/22/3.jpg",
      ],
    },
    {
      id: 23,
      title: "Orange Essence Food Flavou",
      description:
        "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
      price: 14,
      discountPercentage: 8.04,
      rating: 4.85,
      stock: 26,
      brand: "Baking Food Items",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/23/1.jpg",
        "https://i.dummyjson.com/data/products/23/2.jpg",
        "https://i.dummyjson.com/data/products/23/3.jpg",
        "https://i.dummyjson.com/data/products/23/4.jpg",
        "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
      ],
    },
    {
      id: 24,
      title: "cereals muesli fruit nuts",
      description:
        "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
      price: 46,
      discountPercentage: 16.8,
      rating: 4.94,
      stock: 113,
      brand: "fauji",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/24/1.jpg",
        "https://i.dummyjson.com/data/products/24/2.jpg",
        "https://i.dummyjson.com/data/products/24/3.jpg",
        "https://i.dummyjson.com/data/products/24/4.jpg",
        "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
      ],
    },
    {
      id: 25,
      title: "Gulab Powder 50 Gram",
      description:
        "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
      price: 70,
      discountPercentage: 13.58,
      rating: 4.87,
      stock: 47,
      brand: "Dry Rose",
      category: "groceries",
      thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/25/1.png",
        "https://i.dummyjson.com/data/products/25/2.jpg",
        "https://i.dummyjson.com/data/products/25/3.png",
        "https://i.dummyjson.com/data/products/25/4.jpg",
        "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
      ],
    },
    {
      id: 26,
      title: "Plant Hanger For Home",
      description:
        "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
      price: 41,
      discountPercentage: 17.86,
      rating: 4.08,
      stock: 131,
      brand: "Boho Decor",
      category: "home-decoration",
      thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/26/1.jpg",
        "https://i.dummyjson.com/data/products/26/2.jpg",
        "https://i.dummyjson.com/data/products/26/3.jpg",
        "https://i.dummyjson.com/data/products/26/4.jpg",
        "https://i.dummyjson.com/data/products/26/5.jpg",
        "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
      ],
    },
    {
      id: 27,
      title: "Flying Wooden Bird",
      description:
        "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
      price: 51,
      discountPercentage: 15.58,
      rating: 4.41,
      stock: 17,
      brand: "Flying Wooden",
      category: "home-decoration",
      thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/27/1.jpg",
        "https://i.dummyjson.com/data/products/27/2.jpg",
        "https://i.dummyjson.com/data/products/27/3.jpg",
        "https://i.dummyjson.com/data/products/27/4.jpg",
        "https://i.dummyjson.com/data/products/27/thumbnail.webp",
      ],
    },
    {
      id: 28,
      title: "3D Embellishment Art Lamp",
      description:
        "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
      price: 20,
      discountPercentage: 16.49,
      rating: 4.82,
      stock: 54,
      brand: "LED Lights",
      category: "home-decoration",
      thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/28/1.jpg",
        "https://i.dummyjson.com/data/products/28/2.jpg",
        "https://i.dummyjson.com/data/products/28/3.png",
        "https://i.dummyjson.com/data/products/28/4.jpg",
        "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
      ],
    },
    {
      id: 29,
      title: "Handcraft Chinese style",
      description:
        "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
      price: 60,
      discountPercentage: 15.34,
      rating: 4.44,
      stock: 7,
      brand: "luxury palace",
      category: "home-decoration",
      thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.webp",
      images: [
        "https://i.dummyjson.com/data/products/29/1.jpg",
        "https://i.dummyjson.com/data/products/29/2.jpg",
        "https://i.dummyjson.com/data/products/29/3.webp",
        "https://i.dummyjson.com/data/products/29/4.webp",
        "https://i.dummyjson.com/data/products/29/thumbnail.webp",
      ],
    },
    {
      id: 30,
      title: "Key Holder",
      description:
        "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
      price: 30,
      discountPercentage: 2.92,
      rating: 4.92,
      stock: 54,
      brand: "Golden",
      category: "home-decoration",
      thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
      images: [
        "https://i.dummyjson.com/data/products/30/1.jpg",
        "https://i.dummyjson.com/data/products/30/2.jpg",
        "https://i.dummyjson.com/data/products/30/3.jpg",
        "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
      ],
    },
  ],
  total: 100,
  skip: 0,
  limit: 30,
};

export const test2json = {
  default: {
    rankedList: [
      {
        rankedKeyword: [
          {
            topic: {
              mid: "/m/09jcvs",
              title: "YouTube",
              type: "Video sharing company",
            },
            value: 100,
            formattedValue: "100",
            hasData: true,
            link: "/trends/explore?q=/m/09jcvs&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/09lgd",
              title: "Lyrics",
              type: "Topic",
            },
            value: 98,
            formattedValue: "98",
            hasData: true,
            link: "/trends/explore?q=/m/09lgd&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02vxn",
              title: "Film",
              type: "Topic",
            },
            value: 71,
            formattedValue: "71",
            hasData: true,
            link: "/trends/explore?q=/m/02vxn&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/074ft",
              title: "Song",
              type: "Composition type",
            },
            value: 34,
            formattedValue: "34",
            hasData: true,
            link: "/trends/explore?q=/m/074ft&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0jxy",
              title: "Anime",
              type: "Television genre",
            },
            value: 33,
            formattedValue: "33",
            hasData: true,
            link: "/trends/explore?q=/m/0jxy&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/01gp74",
              title: "Chord",
              type: "Music",
            },
            value: 31,
            formattedValue: "31",
            hasData: true,
            link: "/trends/explore?q=/m/01gp74&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02cphr",
              title: "Episode",
              type: "Topic",
            },
            value: 30,
            formattedValue: "30",
            hasData: true,
            link: "/trends/explore?q=/m/02cphr&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02csf",
              title: "Drawing",
              type: "Visual art form",
            },
            value: 27,
            formattedValue: "27",
            hasData: true,
            link: "/trends/explore?q=/m/02csf&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0bh_zc",
              title: "Meaning",
              type: "Topic",
            },
            value: 26,
            formattedValue: "26",
            hasData: true,
            link: "/trends/explore?q=/m/0bh_zc&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/07qv_",
              title: "Tagalog",
              type: "Spoken language",
            },
            value: 23,
            formattedValue: "23",
            hasData: true,
            link: "/trends/explore?q=/m/07qv_&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02h40lc",
              title: "English Language",
              type: "Spoken language",
            },
            value: 23,
            formattedValue: "23",
            hasData: true,
            link: "/trends/explore?q=/m/02h40lc&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0bm3b",
              title: "Download",
              type: "Software",
            },
            value: 21,
            formattedValue: "21",
            hasData: true,
            link: "/trends/explore?q=/m/0bm3b&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/07z4p",
              title: "Video",
              type: "File format",
            },
            value: 20,
            formattedValue: "20",
            hasData: true,
            link: "/trends/explore?q=/m/07z4p&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/05v8c",
              title: "Philippines",
              type: "Country in Asia",
            },
            value: 20,
            formattedValue: "20",
            hasData: true,
            link: "/trends/explore?q=/m/05v8c&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/017rf_",
              title: "Netflix",
              type: "Entertainment company",
            },
            value: 6,
            formattedValue: "6",
            hasData: true,
            link: "/trends/explore?q=/m/017rf_&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/04zc0",
              title: "MP3",
              type: "Format",
            },
            value: 6,
            formattedValue: "6",
            hasData: true,
            link: "/trends/explore?q=/m/04zc0&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11csq95ph6",
              title: "Netflix",
              type: "Topic",
            },
            value: 6,
            formattedValue: "6",
            hasData: true,
            link: "/trends/explore?q=/g/11csq95ph6&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/050rdq",
              title: "Casting",
              type: "Performing arts",
            },
            value: 5,
            formattedValue: "5",
            hasData: true,
            link: "/trends/explore?q=/m/050rdq&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0svqxy7",
              title: "Netflix",
              type: "Website",
            },
            value: 5,
            formattedValue: "5",
            hasData: true,
            link: "/trends/explore?q=/m/0svqxy7&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/071x0k",
              title: "Filipino",
              type: "People",
            },
            value: 4,
            formattedValue: "4",
            hasData: true,
            link: "/trends/explore?q=/m/071x0k&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/04rlf",
              title: "Music",
              type: "Musical arranger",
            },
            value: 4,
            formattedValue: "4",
            hasData: true,
            link: "/trends/explore?q=/m/04rlf&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0446_4",
              title: "Pinoy",
              type: "Topic",
            },
            value: 4,
            formattedValue: "4",
            hasData: true,
            link: "/trends/explore?q=/m/0446_4&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02hwhyv",
              title: "Korean",
              type: "Spoken language",
            },
            value: 4,
            formattedValue: "4",
            hasData: true,
            link: "/trends/explore?q=/m/02hwhyv&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/04spm",
              title: "Manga",
              type: "Art form",
            },
            value: 3,
            formattedValue: "3",
            hasData: true,
            link: "/trends/explore?q=/m/04spm&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/1219h60v",
              title: "Meaning",
              type: "Topic",
            },
            value: 3,
            formattedValue: "3",
            hasData: true,
            link: "/trends/explore?q=/g/1219h60v&date=2022-06-27+2023-06-27&geo=PH",
          },
        ],
      },
      {
        rankedKeyword: [
          {
            topic: {
              mid: "/g/11s7sfpb_9",
              title: "Abot-Kamay na Pangarap",
              type: "Television series",
            },
            value: 1050,
            formattedValue: "+1,050%",
            link: "/trends/explore?q=/g/11s7sfpb_9&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11b77b4nfc",
              title: "2023",
              type: "Topic",
            },
            value: 900,
            formattedValue: "+900%",
            link: "/trends/explore?q=/g/11b77b4nfc&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11jymwgvy2",
              title: "Pasilyo",
              type: "Song by SunKissed Lola",
            },
            value: 700,
            formattedValue: "+700%",
            link: "/trends/explore?q=/g/11jymwgvy2&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02csf",
              title: "Drawing",
              type: "Visual art form",
            },
            value: 400,
            formattedValue: "+400%",
            link: "/trends/explore?q=/m/02csf&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0hzp_sf",
              title: "Bilibili",
              type: "Website",
            },
            value: 350,
            formattedValue: "+350%",
            link: "/trends/explore?q=/m/0hzp_sf&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11csq95ph6",
              title: "Netflix",
              type: "Topic",
            },
            value: 250,
            formattedValue: "+250%",
            link: "/trends/explore?q=/g/11csq95ph6&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/1219h60v",
              title: "Meaning",
              type: "Topic",
            },
            value: 250,
            formattedValue: "+250%",
            link: "/trends/explore?q=/g/1219h60v&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0svqxy7",
              title: "Netflix",
              type: "Website",
            },
            value: 250,
            formattedValue: "+250%",
            link: "/trends/explore?q=/m/0svqxy7&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/07z4p",
              title: "Video",
              type: "File format",
            },
            value: 250,
            formattedValue: "+250%",
            link: "/trends/explore?q=/m/07z4p&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/05v8c",
              title: "Philippines",
              type: "Country in Asia",
            },
            value: 200,
            formattedValue: "+200%",
            link: "/trends/explore?q=/m/05v8c&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0h_m",
              title: "Adventure",
              type: "Topic",
            },
            value: 170,
            formattedValue: "+170%",
            link: "/trends/explore?q=/m/0h_m&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0ryzfx8",
              title: "Spotify",
              type: "Company",
            },
            value: 140,
            formattedValue: "+140%",
            link: "/trends/explore?q=/m/0ryzfx8&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11bc5bnpg8",
              title: "SSS",
              type: "Topic",
            },
            value: 130,
            formattedValue: "+130%",
            link: "/trends/explore?q=/g/11bc5bnpg8&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0kcc7",
              title: "Movie theater",
              type: "Building use",
            },
            value: 130,
            formattedValue: "+130%",
            link: "/trends/explore?q=/m/0kcc7&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/01jddz",
              title: "Concert",
              type: "Topic",
            },
            value: 130,
            formattedValue: "+130%",
            link: "/trends/explore?q=/m/01jddz&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11rpqtj9p7",
              title: "online",
              type: "Topic",
            },
            value: 110,
            formattedValue: "+110%",
            link: "/trends/explore?q=/g/11rpqtj9p7&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11c59p0g8n",
              title: "Google",
              type: "Topic",
            },
            value: 110,
            formattedValue: "+110%",
            link: "/trends/explore?q=/g/11c59p0g8n&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/04l3nj",
              title: ".ph",
              type: "Top-level domain",
            },
            value: 110,
            formattedValue: "+110%",
            link: "/trends/explore?q=/m/04l3nj&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/04yhd6c",
              title: "Spotify",
              type: "Website",
            },
            value: 100,
            formattedValue: "+100%",
            link: "/trends/explore?q=/m/04yhd6c&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0446_4",
              title: "Pinoy",
              type: "Topic",
            },
            value: 90,
            formattedValue: "+90%",
            link: "/trends/explore?q=/m/0446_4&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11b77qrp3l",
              title: "2022",
              type: "Topic",
            },
            value: 90,
            formattedValue: "+90%",
            link: "/trends/explore?q=/g/11b77qrp3l&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/02py351",
              title: "Ticket",
              type: "Admission",
            },
            value: 90,
            formattedValue: "+90%",
            link: "/trends/explore?q=/m/02py351&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/m/0156dy",
              title: "Project",
              type: "Topic",
            },
            value: 90,
            formattedValue: "+90%",
            link: "/trends/explore?q=/m/0156dy&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11bc6ry_g6",
              title: "0",
              type: "Topic",
            },
            value: 90,
            formattedValue: "+90%",
            link: "/trends/explore?q=/g/11bc6ry_g6&date=2022-06-27+2023-06-27&geo=PH",
          },
          {
            topic: {
              mid: "/g/11bc64l86c",
              title: "Bureau of Internal Revenue",
              type: "Topic",
            },
            value: 80,
            formattedValue: "+80%",
            link: "/trends/explore?q=/g/11bc64l86c&date=2022-06-27+2023-06-27&geo=PH",
          },
        ],
      },
    ],
  },
};

export const test3json = {
  default: {
    timelineData: [
      {
        time: "1656806400",
        formattedTime: "Jul 3 – 9, 2022",
        formattedAxisTime: "Jul 3, 2022",
        value: [91],
        hasData: [true],
        formattedValue: ["91"],
      },
      {
        time: "1657411200",
        formattedTime: "Jul 10 – 16, 2022",
        formattedAxisTime: "Jul 10, 2022",
        value: [99],
        hasData: [true],
        formattedValue: ["99"],
      },
      {
        time: "1658016000",
        formattedTime: "Jul 17 – 23, 2022",
        formattedAxisTime: "Jul 17, 2022",
        value: [95],
        hasData: [true],
        formattedValue: ["95"],
      },
      {
        time: "1658620800",
        formattedTime: "Jul 24 – 30, 2022",
        formattedAxisTime: "Jul 24, 2022",
        value: [93],
        hasData: [true],
        formattedValue: ["93"],
      },
      {
        time: "1659225600",
        formattedTime: "Jul 31 – Aug 6, 2022",
        formattedAxisTime: "Jul 31, 2022",
        value: [95],
        hasData: [true],
        formattedValue: ["95"],
      },
      {
        time: "1659830400",
        formattedTime: "Aug 7 – 13, 2022",
        formattedAxisTime: "Aug 7, 2022",
        value: [100],
        hasData: [true],
        formattedValue: ["100"],
      },
      {
        time: "1660435200",
        formattedTime: "Aug 14 – 20, 2022",
        formattedAxisTime: "Aug 14, 2022",
        value: [94],
        hasData: [true],
        formattedValue: ["94"],
      },
      {
        time: "1661040000",
        formattedTime: "Aug 21 – 27, 2022",
        formattedAxisTime: "Aug 21, 2022",
        value: [97],
        hasData: [true],
        formattedValue: ["97"],
      },
      {
        time: "1661644800",
        formattedTime: "Aug 28 – Sep 3, 2022",
        formattedAxisTime: "Aug 28, 2022",
        value: [94],
        hasData: [true],
        formattedValue: ["94"],
      },
      {
        time: "1662249600",
        formattedTime: "Sep 4 – 10, 2022",
        formattedAxisTime: "Sep 4, 2022",
        value: [99],
        hasData: [true],
        formattedValue: ["99"],
      },
      {
        time: "1662854400",
        formattedTime: "Sep 11 – 17, 2022",
        formattedAxisTime: "Sep 11, 2022",
        value: [95],
        hasData: [true],
        formattedValue: ["95"],
      },
      {
        time: "1663459200",
        formattedTime: "Sep 18 – 24, 2022",
        formattedAxisTime: "Sep 18, 2022",
        value: [94],
        hasData: [true],
        formattedValue: ["94"],
      },
      {
        time: "1664064000",
        formattedTime: "Sep 25 – Oct 1, 2022",
        formattedAxisTime: "Sep 25, 2022",
        value: [97],
        hasData: [true],
        formattedValue: ["97"],
      },
      {
        time: "1664668800",
        formattedTime: "Oct 2 – 8, 2022",
        formattedAxisTime: "Oct 2, 2022",
        value: [91],
        hasData: [true],
        formattedValue: ["91"],
      },
      {
        time: "1665273600",
        formattedTime: "Oct 9 – 15, 2022",
        formattedAxisTime: "Oct 9, 2022",
        value: [94],
        hasData: [true],
        formattedValue: ["94"],
      },
      {
        time: "1665878400",
        formattedTime: "Oct 16 – 22, 2022",
        formattedAxisTime: "Oct 16, 2022",
        value: [92],
        hasData: [true],
        formattedValue: ["92"],
      },
      {
        time: "1666483200",
        formattedTime: "Oct 23 – 29, 2022",
        formattedAxisTime: "Oct 23, 2022",
        value: [86],
        hasData: [true],
        formattedValue: ["86"],
      },
      {
        time: "1667088000",
        formattedTime: "Oct 30 – Nov 5, 2022",
        formattedAxisTime: "Oct 30, 2022",
        value: [90],
        hasData: [true],
        formattedValue: ["90"],
      },
      {
        time: "1667692800",
        formattedTime: "Nov 6 – 12, 2022",
        formattedAxisTime: "Nov 6, 2022",
        value: [91],
        hasData: [true],
        formattedValue: ["91"],
      },
      {
        time: "1668297600",
        formattedTime: "Nov 13 – 19, 2022",
        formattedAxisTime: "Nov 13, 2022",
        value: [100],
        hasData: [true],
        formattedValue: ["100"],
      },
      {
        time: "1668902400",
        formattedTime: "Nov 20 – 26, 2022",
        formattedAxisTime: "Nov 20, 2022",
        value: [96],
        hasData: [true],
        formattedValue: ["96"],
      },
      {
        time: "1669507200",
        formattedTime: "Nov 27 – Dec 3, 2022",
        formattedAxisTime: "Nov 27, 2022",
        value: [88],
        hasData: [true],
        formattedValue: ["88"],
      },
      {
        time: "1670112000",
        formattedTime: "Dec 4 – 10, 2022",
        formattedAxisTime: "Dec 4, 2022",
        value: [87],
        hasData: [true],
        formattedValue: ["87"],
      },
      {
        time: "1670716800",
        formattedTime: "Dec 11 – 17, 2022",
        formattedAxisTime: "Dec 11, 2022",
        value: [88],
        hasData: [true],
        formattedValue: ["88"],
      },
      {
        time: "1671321600",
        formattedTime: "Dec 18 – 24, 2022",
        formattedAxisTime: "Dec 18, 2022",
        value: [42],
        hasData: [true],
        formattedValue: ["42"],
      },
      {
        time: "1671926400",
        formattedTime: "Dec 25 – 31, 2022",
        formattedAxisTime: "Dec 25, 2022",
        value: [93],
        hasData: [true],
        formattedValue: ["93"],
      },
      {
        time: "1672531200",
        formattedTime: "Jan 1 – 7, 2023",
        formattedAxisTime: "Jan 1, 2023",
        value: [95],
        hasData: [true],
        formattedValue: ["95"],
      },
      {
        time: "1673136000",
        formattedTime: "Jan 8 – 14, 2023",
        formattedAxisTime: "Jan 8, 2023",
        value: [92],
        hasData: [true],
        formattedValue: ["92"],
      },
      {
        time: "1673740800",
        formattedTime: "Jan 15 – 21, 2023",
        formattedAxisTime: "Jan 15, 2023",
        value: [90],
        hasData: [true],
        formattedValue: ["90"],
      },
      {
        time: "1674345600",
        formattedTime: "Jan 22 – 28, 2023",
        formattedAxisTime: "Jan 22, 2023",
        value: [88],
        hasData: [true],
        formattedValue: ["88"],
      },
      {
        time: "1674950400",
        formattedTime: "Jan 29 – Feb 4, 2023",
        formattedAxisTime: "Jan 29, 2023",
        value: [91],
        hasData: [true],
        formattedValue: ["91"],
      },
      {
        time: "1675555200",
        formattedTime: "Feb 5 – 11, 2023",
        formattedAxisTime: "Feb 5, 2023",
        value: [89],
        hasData: [true],
        formattedValue: ["89"],
      },
      {
        time: "1676160000",
        formattedTime: "Feb 12 – 18, 2023",
        formattedAxisTime: "Feb 12, 2023",
        value: [89],
        hasData: [true],
        formattedValue: ["89"],
      },
      {
        time: "1676764800",
        formattedTime: "Feb 19 – 25, 2023",
        formattedAxisTime: "Feb 19, 2023",
        value: [92],
        hasData: [true],
        formattedValue: ["92"],
      },
      {
        time: "1677369600",
        formattedTime: "Feb 26 – Mar 4, 2023",
        formattedAxisTime: "Feb 26, 2023",
        value: [90],
        hasData: [true],
        formattedValue: ["90"],
      },
      {
        time: "1677974400",
        formattedTime: "Mar 5 – 11, 2023",
        formattedAxisTime: "Mar 5, 2023",
        value: [94],
        hasData: [true],
        formattedValue: ["94"],
      },
      {
        time: "1678579200",
        formattedTime: "Mar 12 – 18, 2023",
        formattedAxisTime: "Mar 12, 2023",
        value: [95],
        hasData: [true],
        formattedValue: ["95"],
      },
      {
        time: "1679184000",
        formattedTime: "Mar 19 – 25, 2023",
        formattedAxisTime: "Mar 19, 2023",
        value: [90],
        hasData: [true],
        formattedValue: ["90"],
      },
      {
        time: "1679788800",
        formattedTime: "Mar 26 – Apr 1, 2023",
        formattedAxisTime: "Mar 26, 2023",
        value: [88],
        hasData: [true],
        formattedValue: ["88"],
      },
      {
        time: "1680393600",
        formattedTime: "Apr 2 – 8, 2023",
        formattedAxisTime: "Apr 2, 2023",
        value: [89],
        hasData: [true],
        formattedValue: ["89"],
      },
      {
        time: "1680998400",
        formattedTime: "Apr 9 – 15, 2023",
        formattedAxisTime: "Apr 9, 2023",
        value: [88],
        hasData: [true],
        formattedValue: ["88"],
      },
      {
        time: "1681603200",
        formattedTime: "Apr 16 – 22, 2023",
        formattedAxisTime: "Apr 16, 2023",
        value: [94],
        hasData: [true],
        formattedValue: ["94"],
      },
      {
        time: "1682208000",
        formattedTime: "Apr 23 – 29, 2023",
        formattedAxisTime: "Apr 23, 2023",
        value: [86],
        hasData: [true],
        formattedValue: ["86"],
      },
      {
        time: "1682812800",
        formattedTime: "Apr 30 – May 6, 2023",
        formattedAxisTime: "Apr 30, 2023",
        value: [81],
        hasData: [true],
        formattedValue: ["81"],
      },
      {
        time: "1683417600",
        formattedTime: "May 7 – 13, 2023",
        formattedAxisTime: "May 7, 2023",
        value: [87],
        hasData: [true],
        formattedValue: ["87"],
      },
      {
        time: "1684022400",
        formattedTime: "May 14 – 20, 2023",
        formattedAxisTime: "May 14, 2023",
        value: [90],
        hasData: [true],
        formattedValue: ["90"],
      },
      {
        time: "1684627200",
        formattedTime: "May 21 – 27, 2023",
        formattedAxisTime: "May 21, 2023",
        value: [90],
        hasData: [true],
        formattedValue: ["90"],
      },
      {
        time: "1685232000",
        formattedTime: "May 28 – Jun 3, 2023",
        formattedAxisTime: "May 28, 2023",
        value: [92],
        hasData: [true],
        formattedValue: ["92"],
      },
      {
        time: "1685836800",
        formattedTime: "Jun 4 – 10, 2023",
        formattedAxisTime: "Jun 4, 2023",
        value: [92],
        hasData: [true],
        formattedValue: ["92"],
      },
      {
        time: "1686441600",
        formattedTime: "Jun 11 – 17, 2023",
        formattedAxisTime: "Jun 11, 2023",
        value: [87],
        hasData: [true],
        formattedValue: ["87"],
      },
      {
        time: "1687046400",
        formattedTime: "Jun 18 – 24, 2023",
        formattedAxisTime: "Jun 18, 2023",
        value: [30],
        hasData: [true],
        formattedValue: ["30"],
        isPartial: true,
      },
    ],
    averages: [],
  },
};
